/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2015-07-09 02:32:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.edaisong.entity.BusinessBalanceRecord;

public final class notImplement_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.edaisong.entity.BusinessBalanceRecord");
    _jspx_imports_classes.add("java.util.List");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("         \r\n");
      out.write(" \r\n");
      out.write("<div class=\"row  border-bottom white-bg dashboard-header\">\r\n");
      out.write("\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t<blockquote class=\"text-danger\">\r\n");
      out.write("\t\t\t<h1>此功能还未实现，更多精品敬请期待…………</h1>\r\n");
      out.write("\t\t\t<h2>亲，先随便看看吧....</h2>\r\n");
      out.write("\t\t</blockquote>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t充值流水记录列表：\r\n");
      out.write("\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr class=\"tdbg\">\r\n");
      out.write("\t\t\t\t\t<th width=\"%5\">id</th>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"%5\">BusinessId</th>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"%5\">Operator</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t");

		List<BusinessBalanceRecord> data=	(List<BusinessBalanceRecord>)request.getAttribute("listData");
		 for (int i = 0; i < data.size(); i++) {
			 
      out.write("  \r\n");
      out.write("\t\t\t <tr>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(data.get(i).getId() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(data.get(i).getBusinessId() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(data.get(i).getOperator() );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t ");
}
		
      out.write(" \r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t<blockquote class=\"text-warning\" style=\"font-size: 14px\">\r\n");
      out.write("\t\t\t<h3>\r\n");
      out.write("\t\t\t\tE代送 <a target=\"_blank\" href=\"http://www.edaisong.com\">edaisong.com</a>\r\n");
      out.write("\t\t\t</h3>\r\n");
      out.write("\t\t\t是物流需求发起与即时响应的信息共享及服务网络。<br> 您是否一直在苦苦寻找能为您解决即时配送服务的伙伴？ <br>您是否想利用闲散时间赚一些零花钱？<br>\r\n");
      out.write("\t\t\t…………\r\n");
      out.write("\t\t\t<h4 class=\"text-danger\">那么，现在E代送来了</h4>\r\n");
      out.write("\t\t</blockquote>\r\n");
      out.write("\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"wrapper wrapper-content\">\r\n");
      out.write("\t\t<div class=\"row animated fadeInRight\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t<div class=\"ibox float-e-margins\">\r\n");
      out.write("\t\t\t\t\t<div class=\"text-center float-e-margins p-md\">\r\n");
      out.write("\t\t\t\t\t\t<span>E代送系统发展里程碑</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"ibox-content\" id=\"ibox-content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div id=\"vertical-timeline\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"vertical-container dark-timeline center-orientation\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"vertical-timeline-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"vertical-timeline-icon navy-bg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-briefcase\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"vertical-timeline-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2>充值上线啦！</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>充值功能上线，不可否认，具有划时代的意义.充值功能上线，不可否认，具有划时代的意义.充值功能上线，不可否认，具有划时代的意义.充值功能上线，不可否认，具有划时代的意义.充值功能上线，不可否认，具有划时代的意义.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-sm btn-primary\"> 更多信息</a> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"vertical-date\"> 1月份 <br> <small>01-15</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"vertical-timeline-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"vertical-timeline-icon blue-bg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-file-text\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"vertical-timeline-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2>V2.0上线啦！</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>2.0版本的上线，意义重大，从此刻开始，我们再也不从再回款问题了？\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t2.0版本的上线，意义重大，从此刻开始，我们再也不从再回款问题了？\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t2.0版本的上线，意义重大，从此刻开始，我们再也不从再回款问题了？\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t2.0版本的上线，意义重大，从此刻开始，我们再也不从再回款问题了？</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-sm btn-success\"> 更多 document </a> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"vertical-date\"> 1月份 <br> <small>01-15</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"vertical-timeline-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"vertical-timeline-icon lazur-bg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-coffee\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"vertical-timeline-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2>后台大改版</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Go to shop and find some products. Lorem Ipsum is simply\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdummy text of the printing and typesetting industry. Lorem\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tIpsum has been the industry's.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-sm btn-info\">Read more</a> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"vertical-date\"> 1月份 <br> <small>01-15</small></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"vertical-timeline-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"vertical-timeline-icon yellow-bg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-phone\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"vertical-timeline-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2>Phone with Jeronimo</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\telit. Iusto, optio, dolorum provident rerum aut hic quasi\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceat iure tempora laudantium ipsa ad debitis unde? Iste\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvoluptatibus minus veritatis qui ut.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"vertical-date\">1月份 <br> <small>01-15</small></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"vertical-timeline-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"vertical-timeline-icon lazur-bg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-user-md\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"vertical-timeline-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2>Go to the doctor dr Smith</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Find some issue and go to doctor. Lorem Ipsum is simply\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdummy text of the printing and typesetting industry. Lorem\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tIpsum has been the industry's standard dummy text ever since\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tthe 1500s.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"vertical-date\">1月份 <br> <small>01-15</small></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"vertical-timeline-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"vertical-timeline-icon navy-bg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-comments\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"vertical-timeline-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2>E代送诞生了</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>E代送自2015年1月正式诞生，开始它不平凡的一生。E代送自2015年1月正式诞生，开始它不平凡的一生。E代送自2015年1月正式诞生，开始它不平凡的一生。E代送自2015年1月正式诞生，开始它不平凡的一生。</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"vertical-date\">1月 份<br> <small>01-15</small></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
