/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2015-07-08 09:39:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.template;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/EtaoJavaProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/admin/WEB-INF/lib/tiles-jsp-3.0.5.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1411313530000L));
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-3.0.5.jar", Long.valueOf(1435848268796L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String basePath = request.getContextPath();

      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-static-top\" role=\"navigation\" style=\"margin-bottom: 0\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("        <a class=\"navbar-minimalize minimalize-styl-2 btn btn-primary \" href=\"#\"><i class=\"fa fa-bars\"></i> </a>\r\n");
      out.write("<!--         <form role=\"search\" class=\"navbar-form-custom\" action=\"search_results.html\"> -->\r\n");
      out.write("<!--             <div class=\"form-group\"> -->\r\n");
      out.write("<!--                 <input type=\"text\" placeholder=\"搜索点什么？...\" class=\"form-control\" name=\"top-search\" id=\"top-search\"> -->\r\n");
      out.write("<!--             </div> -->\r\n");
      out.write("<!--         </form> -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <ul class=\"nav navbar-top-links navbar-right\">\r\n");
      out.write("        <li>\r\n");
      out.write("            <span class=\"m-r-sm text-muted welcome-message\">欢迎您使用e代送管理系统.</span>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"dropdown\">\r\n");
      out.write("            <a class=\"dropdown-toggle count-info\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("                <i class=\"fa fa-envelope\"></i>  <span class=\"label label-warning\">16</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"dropdown-menu dropdown-messages\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <div class=\"dropdown-messages-box\">\r\n");
      out.write("                        <a href=\"profile.html\" class=\"pull-left\">\r\n");
      out.write("                            <img alt=\"image\" class=\"img-circle\" src=\"");
      out.print(basePath);
      out.write("/img/a7.jpg\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"media-body\">\r\n");
      out.write("                            <small class=\"pull-right\">46小时 前</small>\r\n");
      out.write("                            <strong>Mike Loreipsum</strong> started following <strong>Monica Smith</strong>. <br>\r\n");
      out.write("                            <small class=\"text-muted\">3 days ago at 7:58 pm - 10.06.2014</small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"divider\"></li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <div class=\"dropdown-messages-box\">\r\n");
      out.write("                        <a href=\"profile.html\" class=\"pull-left\">\r\n");
      out.write("                            <img alt=\"image\" class=\"img-circle\" src=\"");
      out.print(basePath);
      out.write("/img/a4.jpg\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"media-body \">\r\n");
      out.write("                            <small class=\"pull-right text-navy\">5h ago</small>\r\n");
      out.write("                            <strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br>\r\n");
      out.write("                            <small class=\"text-muted\">Yesterday 1:21 pm - 11.06.2014</small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"divider\"></li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <div class=\"dropdown-messages-box\">\r\n");
      out.write("                        <a href=\"profile.html\" class=\"pull-left\">\r\n");
      out.write("                            <img alt=\"image\" class=\"img-circle\" src=\"");
      out.print(basePath);
      out.write("/img/profile.jpg\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"media-body \">\r\n");
      out.write("                            <small class=\"pull-right\">23h ago</small>\r\n");
      out.write("                            <strong>Monica Smith</strong> love <strong>Kim Smith</strong>. <br>\r\n");
      out.write("                            <small class=\"text-muted\">2 days ago at 2:30 am - 11.06.2014</small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"divider\"></li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <div class=\"text-center link-block\">\r\n");
      out.write("                        <a href=\"mailbox.html\">\r\n");
      out.write("                            <i class=\"fa fa-envelope\"></i> <strong>Read All Messages</strong>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"dropdown\">\r\n");
      out.write("            <a class=\"dropdown-toggle count-info\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("                <i class=\"fa fa-bell\"></i>  <span class=\"label label-primary\">8</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"dropdown-menu dropdown-alerts\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"mailbox.html\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <i class=\"fa fa-envelope fa-fw\"></i> 你有16条未读消息\r\n");
      out.write("                            <span class=\"pull-right text-muted small\">4 minutes ago</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"divider\"></li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"profile.html\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <i class=\"fa fa-twitter fa-fw\"></i> 3 New Followers\r\n");
      out.write("                            <span class=\"pull-right text-muted small\">12 minutes ago</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"divider\"></li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"grid_options.html\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <i class=\"fa fa-upload fa-fw\"></i> Server Rebooted\r\n");
      out.write("                            <span class=\"pull-right text-muted small\">4 minutes ago</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"divider\"></li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <div class=\"text-center link-block\">\r\n");
      out.write("                        <a href=\"notifications.html\">\r\n");
      out.write("                            <strong>浏览所有消息</strong>\r\n");
      out.write("                            <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href=\"login.html\">\r\n");
      out.write("                <i class=\"fa fa-sign-out\"></i> 注销\r\n");
      out.write("            </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <a class=\"right-sidebar-toggle\">\r\n");
      out.write("                <i class=\"fa fa-tasks\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</nav>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
