/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2015-07-09 05:58:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.template;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class layout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/EtaoJavaProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/admin/WEB-INF/lib/tiles-jsp-3.0.5.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1411313530000L));
    _jspx_dependants.put("jar:file:/D:/EtaoJavaProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/admin/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-3.0.5.jar", Long.valueOf(1435848268796L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1435834339131L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");

	String basePath = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>");
      if (_jspx_meth_tiles_005fgetAsString_005f0(_jspx_page_context))
        return;
      out.write("</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(basePath);
      out.write("/css/bootstrap.min.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(basePath);
      out.write("/font-awesome/css/font-awesome.min.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(basePath);
      out.write("/css/plugins/toastr/toastr.min.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(basePath);
      out.write("/js/plugins/gritter/jquery.gritter.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(basePath);
      out.write("/css/animate.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(basePath);
      out.write("/css/style.css\" />\r\n");
      out.write("\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_tiles_005finsertAttribute_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("        <div id=\"wrapper\">\r\n");
      out.write("            ");
      if (_jspx_meth_tiles_005finsertAttribute_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            <div id=\"page-wrapper\" class=\"gray-bg dashbard-1\">\r\n");
      out.write("                <div class=\"row border-bottom\">\r\n");
      out.write("                    ");
      if (_jspx_meth_tiles_005finsertAttribute_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
      if (_jspx_meth_tiles_005finsertAttribute_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                \t<div class=\"col-lg-12\">\r\n");
      out.write("                \t");
      if (_jspx_meth_tiles_005finsertAttribute_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("     \r\n");
      out.write("                \t</div>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"\">\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"small-chat-box fadeInRight animated\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"heading\" draggable=\"true\">\r\n");
      out.write("                    <small class=\"chat-date pull-right\">\r\n");
      out.write("                        02.19.2015\r\n");
      out.write("                    </small>\r\n");
      out.write("                    Small chat\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"left\">\r\n");
      out.write("                        <div class=\"author-name\">\r\n");
      out.write("                            Monica Jackson <small class=\"chat-date\">\r\n");
      out.write("                                10:02 am\r\n");
      out.write("                            </small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"chat-message active\">\r\n");
      out.write("                            Lorem Ipsum is simply dummy text input.\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"right\">\r\n");
      out.write("                        <div class=\"author-name\">\r\n");
      out.write("                            Mick Smith\r\n");
      out.write("                            <small class=\"chat-date\">\r\n");
      out.write("                                11:24 am\r\n");
      out.write("                            </small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"chat-message\">\r\n");
      out.write("                            Lorem Ipsum is simpl.\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"left\">\r\n");
      out.write("                        <div class=\"author-name\">\r\n");
      out.write("                            Alice Novak\r\n");
      out.write("                            <small class=\"chat-date\">\r\n");
      out.write("                                08:45 pm\r\n");
      out.write("                            </small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"chat-message active\">\r\n");
      out.write("                            Check this stock char.\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"right\">\r\n");
      out.write("                        <div class=\"author-name\">\r\n");
      out.write("                            Anna Lamson\r\n");
      out.write("                            <small class=\"chat-date\">\r\n");
      out.write("                                11:24 am\r\n");
      out.write("                            </small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"chat-message\">\r\n");
      out.write("                            The standard chunk of Lorem Ipsum\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"left\">\r\n");
      out.write("                        <div class=\"author-name\">\r\n");
      out.write("                            Mick Lane\r\n");
      out.write("                            <small class=\"chat-date\">\r\n");
      out.write("                                08:45 pm\r\n");
      out.write("                            </small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"chat-message active\">\r\n");
      out.write("                            I belive that. Lorem Ipsum is simply dummy text.\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-chat\">\r\n");
      out.write("                    <div class=\"input-group input-group-sm\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\"> <span class=\"input-group-btn\">\r\n");
      out.write("                            <button class=\"btn btn-primary\" type=\"button\">\r\n");
      out.write("                                Send\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"small-chat\">\r\n");
      out.write("\r\n");
      out.write("                <span class=\"badge badge-warning pull-right\">5</span>\r\n");
      out.write("                <a class=\"open-small-chat\">\r\n");
      out.write("                    <i class=\"fa fa-comments\"></i>\r\n");
      out.write("\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"right-sidebar\">\r\n");
      out.write("                <div class=\"sidebar-container\">\r\n");
      out.write("\r\n");
      out.write("                    <ul class=\"nav nav-tabs navs-3\">\r\n");
      out.write("\r\n");
      out.write("                        <li class=\"active\">\r\n");
      out.write("                            <a data-toggle=\"tab\" href=\"#tab-1\">\r\n");
      out.write("                                Notes\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a data-toggle=\"tab\" href=\"#tab-2\">\r\n");
      out.write("                                Projects\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"\">\r\n");
      out.write("                            <a data-toggle=\"tab\" href=\"#tab-3\">\r\n");
      out.write("                                <i class=\"fa fa-gear\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"tab-content\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <div id=\"tab-1\" class=\"tab-pane active\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"sidebar-title\">\r\n");
      out.write("                                <h3> <i class=\"fa fa-comments-o\"></i> Latest Notes</h3>\r\n");
      out.write("                                <small><i class=\"fa fa-tim\"></i> You have 10 new message.</small>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"sidebar-message\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <div class=\"pull-left text-center\">\r\n");
      out.write("                                            <img alt=\"image\" class=\"img-circle message-avatar\" src=\"");
      out.print(basePath);
      out.write("/img/a1.jpg\">\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"m-t-xs\">\r\n");
      out.write("                                                <i class=\"fa fa-star text-warning\"></i>\r\n");
      out.write("                                                <i class=\"fa fa-star text-warning\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("\r\n");
      out.write("                                            There are many variations of passages of Lorem Ipsum available.\r\n");
      out.write("                                            <br>\r\n");
      out.write("                                            <small class=\"text-muted\">Today 4:21 pm</small>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"sidebar-message\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <div class=\"pull-left text-center\">\r\n");
      out.write("                                            <img alt=\"image\" class=\"img-circle message-avatar\" src=\"");
      out.print(basePath);
      out.write("/img/a2.jpg\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            The point of using Lorem Ipsum is that it has a more-or-less normal.\r\n");
      out.write("                                            <br>\r\n");
      out.write("                                            <small class=\"text-muted\">Yesterday 2:45 pm</small>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"sidebar-message\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <div class=\"pull-left text-center\">\r\n");
      out.write("                                            <img alt=\"image\" class=\"img-circle message-avatar\" src=\"");
      out.print(basePath);
      out.write("/img/a3.jpg\">\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"m-t-xs\">\r\n");
      out.write("                                                <i class=\"fa fa-star text-warning\"></i>\r\n");
      out.write("                                                <i class=\"fa fa-star text-warning\"></i>\r\n");
      out.write("                                                <i class=\"fa fa-star text-warning\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            Mevolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).\r\n");
      out.write("                                            <br>\r\n");
      out.write("                                            <small class=\"text-muted\">Yesterday 1:10 pm</small>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"sidebar-message\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <div class=\"pull-left text-center\">\r\n");
      out.write("                                            <img alt=\"image\" class=\"img-circle message-avatar\" src=\"");
      out.print(basePath);
      out.write("/img/a4.jpg\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the\r\n");
      out.write("                                            <br>\r\n");
      out.write("                                            <small class=\"text-muted\">Monday 8:37 pm</small>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"sidebar-message\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <div class=\"pull-left text-center\">\r\n");
      out.write("                                            <img alt=\"image\" class=\"img-circle message-avatar\" src=\"");
      out.print(basePath);
      out.write("/img/a8.jpg\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("\r\n");
      out.write("                                            All the Lorem Ipsum generators on the Internet tend to repeat.\r\n");
      out.write("                                            <br>\r\n");
      out.write("                                            <small class=\"text-muted\">Today 4:21 pm</small>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"sidebar-message\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <div class=\"pull-left text-center\">\r\n");
      out.write("                                            <img alt=\"image\" class=\"img-circle message-avatar\" src=\"");
      out.print(basePath);
      out.write("/img/a7.jpg\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.\r\n");
      out.write("                                            <br>\r\n");
      out.write("                                            <small class=\"text-muted\">Yesterday 2:45 pm</small>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"sidebar-message\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <div class=\"pull-left text-center\">\r\n");
      out.write("                                            <img alt=\"image\" class=\"img-circle message-avatar\" src=\"");
      out.print(basePath);
      out.write("/img/a3.jpg\">\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"m-t-xs\">\r\n");
      out.write("                                                <i class=\"fa fa-star text-warning\"></i>\r\n");
      out.write("                                                <i class=\"fa fa-star text-warning\"></i>\r\n");
      out.write("                                                <i class=\"fa fa-star text-warning\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            The standard chunk of Lorem Ipsum used since the 1500s is reproduced below.\r\n");
      out.write("                                            <br>\r\n");
      out.write("                                            <small class=\"text-muted\">Yesterday 1:10 pm</small>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"sidebar-message\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <div class=\"pull-left text-center\">\r\n");
      out.write("                                            <img alt=\"image\" class=\"img-circle message-avatar\" src=\"");
      out.print(basePath);
      out.write("/img/a4.jpg\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"media-body\">\r\n");
      out.write("                                            Uncover many web sites still in their infancy. Various versions have.\r\n");
      out.write("                                            <br>\r\n");
      out.write("                                            <small class=\"text-muted\">Monday 8:37 pm</small>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div id=\"tab-2\" class=\"tab-pane\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"sidebar-title\">\r\n");
      out.write("                                <h3> <i class=\"fa fa-cube\"></i> Latest projects</h3>\r\n");
      out.write("                                <small><i class=\"fa fa-tim\"></i> You have 14 projects. 10 not completed.</small>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <ul class=\"sidebar-list\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <div class=\"small pull-right m-t-xs\">9 hours ago</div>\r\n");
      out.write("                                        <h4>Business valuation</h4>\r\n");
      out.write("                                        It is a long established fact that a reader will be distracted.\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"small\">Completion with: 22%</div>\r\n");
      out.write("                                        <div class=\"progress progress-mini\">\r\n");
      out.write("                                            <div style=\"width: 22%;\" class=\"progress-bar progress-bar-warning\"></div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"small text-muted m-t-xs\">Project end: 4:00 pm - 12.06.2014</div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <div class=\"small pull-right m-t-xs\">9 hours ago</div>\r\n");
      out.write("                                        <h4>Contract with Company </h4>\r\n");
      out.write("                                        Many desktop publishing packages and web page editors.\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"small\">Completion with: 48%</div>\r\n");
      out.write("                                        <div class=\"progress progress-mini\">\r\n");
      out.write("                                            <div style=\"width: 48%;\" class=\"progress-bar\"></div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <div class=\"small pull-right m-t-xs\">9 hours ago</div>\r\n");
      out.write("                                        <h4>Meeting</h4>\r\n");
      out.write("                                        By the readable content of a page when looking at its layout.\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"small\">Completion with: 14%</div>\r\n");
      out.write("                                        <div class=\"progress progress-mini\">\r\n");
      out.write("                                            <div style=\"width: 14%;\" class=\"progress-bar progress-bar-info\"></div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <span class=\"label label-primary pull-right\">NEW</span>\r\n");
      out.write("                                        <h4>The generated</h4>\r\n");
      out.write("                                        <!--<div class=\"small pull-right m-t-xs\">9 hours ago</div>-->\r\n");
      out.write("                                        There are many variations of passages of Lorem Ipsum available.\r\n");
      out.write("                                        <div class=\"small\">Completion with: 22%</div>\r\n");
      out.write("                                        <div class=\"small text-muted m-t-xs\">Project end: 4:00 pm - 12.06.2014</div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <div class=\"small pull-right m-t-xs\">9 hours ago</div>\r\n");
      out.write("                                        <h4>Business valuation</h4>\r\n");
      out.write("                                        It is a long established fact that a reader will be distracted.\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"small\">Completion with: 22%</div>\r\n");
      out.write("                                        <div class=\"progress progress-mini\">\r\n");
      out.write("                                            <div style=\"width: 22%;\" class=\"progress-bar progress-bar-warning\"></div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"small text-muted m-t-xs\">Project end: 4:00 pm - 12.06.2014</div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <div class=\"small pull-right m-t-xs\">9 hours ago</div>\r\n");
      out.write("                                        <h4>Contract with Company </h4>\r\n");
      out.write("                                        Many desktop publishing packages and web page editors.\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"small\">Completion with: 48%</div>\r\n");
      out.write("                                        <div class=\"progress progress-mini\">\r\n");
      out.write("                                            <div style=\"width: 48%;\" class=\"progress-bar\"></div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <div class=\"small pull-right m-t-xs\">9 hours ago</div>\r\n");
      out.write("                                        <h4>Meeting</h4>\r\n");
      out.write("                                        By the readable content of a page when looking at its layout.\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"small\">Completion with: 14%</div>\r\n");
      out.write("                                        <div class=\"progress progress-mini\">\r\n");
      out.write("                                            <div style=\"width: 14%;\" class=\"progress-bar progress-bar-info\"></div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <span class=\"label label-primary pull-right\">NEW</span>\r\n");
      out.write("                                        <h4>The generated</h4>\r\n");
      out.write("                                        <!--<div class=\"small pull-right m-t-xs\">9 hours ago</div>-->\r\n");
      out.write("                                        There are many variations of passages of Lorem Ipsum available.\r\n");
      out.write("                                        <div class=\"small\">Completion with: 22%</div>\r\n");
      out.write("                                        <div class=\"small text-muted m-t-xs\">Project end: 4:00 pm - 12.06.2014</div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("\r\n");
      out.write("                            </ul>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div id=\"tab-3\" class=\"tab-pane\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"sidebar-title\">\r\n");
      out.write("                                <h3><i class=\"fa fa-gears\"></i> Settings</h3>\r\n");
      out.write("                                <small><i class=\"fa fa-tim\"></i> You have 14 projects. 10 not completed.</small>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"setings-item\">\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    Show notifications\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <div class=\"switch\">\r\n");
      out.write("                                    <div class=\"onoffswitch\">\r\n");
      out.write("                                        <input type=\"checkbox\" name=\"collapsemenu\" class=\"onoffswitch-checkbox\" id=\"example\">\r\n");
      out.write("                                        <label class=\"onoffswitch-label\" for=\"example\">\r\n");
      out.write("                                            <span class=\"onoffswitch-inner\"></span>\r\n");
      out.write("                                            <span class=\"onoffswitch-switch\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"setings-item\">\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    Disable Chat\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <div class=\"switch\">\r\n");
      out.write("                                    <div class=\"onoffswitch\">\r\n");
      out.write("                                        <input type=\"checkbox\" name=\"collapsemenu\" checked class=\"onoffswitch-checkbox\" id=\"example2\">\r\n");
      out.write("                                        <label class=\"onoffswitch-label\" for=\"example2\">\r\n");
      out.write("                                            <span class=\"onoffswitch-inner\"></span>\r\n");
      out.write("                                            <span class=\"onoffswitch-switch\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"setings-item\">\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    Enable history\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <div class=\"switch\">\r\n");
      out.write("                                    <div class=\"onoffswitch\">\r\n");
      out.write("                                        <input type=\"checkbox\" name=\"collapsemenu\" class=\"onoffswitch-checkbox\" id=\"example3\">\r\n");
      out.write("                                        <label class=\"onoffswitch-label\" for=\"example3\">\r\n");
      out.write("                                            <span class=\"onoffswitch-inner\"></span>\r\n");
      out.write("                                            <span class=\"onoffswitch-switch\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"setings-item\">\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    Show charts\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <div class=\"switch\">\r\n");
      out.write("                                    <div class=\"onoffswitch\">\r\n");
      out.write("                                        <input type=\"checkbox\" name=\"collapsemenu\" class=\"onoffswitch-checkbox\" id=\"example4\">\r\n");
      out.write("                                        <label class=\"onoffswitch-label\" for=\"example4\">\r\n");
      out.write("                                            <span class=\"onoffswitch-inner\"></span>\r\n");
      out.write("                                            <span class=\"onoffswitch-switch\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"setings-item\">\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    Offline users\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <div class=\"switch\">\r\n");
      out.write("                                    <div class=\"onoffswitch\">\r\n");
      out.write("                                        <input type=\"checkbox\" checked name=\"collapsemenu\" class=\"onoffswitch-checkbox\" id=\"example5\">\r\n");
      out.write("                                        <label class=\"onoffswitch-label\" for=\"example5\">\r\n");
      out.write("                                            <span class=\"onoffswitch-inner\"></span>\r\n");
      out.write("                                            <span class=\"onoffswitch-switch\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"setings-item\">\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    Global search\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <div class=\"switch\">\r\n");
      out.write("                                    <div class=\"onoffswitch\">\r\n");
      out.write("                                        <input type=\"checkbox\" checked name=\"collapsemenu\" class=\"onoffswitch-checkbox\" id=\"example6\">\r\n");
      out.write("                                        <label class=\"onoffswitch-label\" for=\"example6\">\r\n");
      out.write("                                            <span class=\"onoffswitch-inner\"></span>\r\n");
      out.write("                                            <span class=\"onoffswitch-switch\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"setings-item\">\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    Update everyday\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <div class=\"switch\">\r\n");
      out.write("                                    <div class=\"onoffswitch\">\r\n");
      out.write("                                        <input type=\"checkbox\" name=\"collapsemenu\" class=\"onoffswitch-checkbox\" id=\"example7\">\r\n");
      out.write("                                        <label class=\"onoffswitch-label\" for=\"example7\">\r\n");
      out.write("                                            <span class=\"onoffswitch-inner\"></span>\r\n");
      out.write("                                            <span class=\"onoffswitch-switch\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"sidebar-content\">\r\n");
      out.write("                                <h4>Settings</h4>\r\n");
      out.write("                                <div class=\"small\">\r\n");
      out.write("                                    I belive that. Lorem Ipsum is simply dummy text of the printing and typesetting industry.\r\n");
      out.write("                                    And typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.\r\n");
      out.write("                                    Over the years, sometimes by accident, sometimes on purpose (injected humour and the like).\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Mainly scripts -->\r\n");
      out.write("        <script src=\"");
      out.print(basePath);
      out.write("/js/jquery-2.1.1.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(basePath);
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(basePath);
      out.write("/js/plugins/metisMenu/jquery.metisMenu.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(basePath);
      out.write("/js/plugins/slimscroll/jquery.slimscroll.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <!-- Flot -->\r\n");
      out.write("        <script src=\"");
      out.print(basePath);
      out.write("/js/plugins/flot/jquery.flot.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(basePath);
      out.write("/js/plugins/flot/jquery.flot.tooltip.min.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(basePath);
      out.write("/js/plugins/flot/jquery.flot.spline.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(basePath);
      out.write("/js/plugins/flot/jquery.flot.resize.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(basePath);
      out.write("/js/plugins/flot/jquery.flot.pie.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <!-- Peity -->\r\n");
      out.write("        <script src=\"");
      out.print(basePath);
      out.write("/js/plugins/peity/jquery.peity.min.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(basePath);
      out.write("/js/demo/peity-demo.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <!-- Custom and plugin javascript -->\r\n");
      out.write("        <script src=\"");
      out.print(basePath);
      out.write("/js/inspinia.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.print(basePath);
      out.write("/js/plugins/pace/pace.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <!-- jQuery UI -->\r\n");
      out.write("        <script src=\"");
      out.print(basePath);
      out.write("/js/plugins/jquery-ui/jquery-ui.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <!-- GITTER -->\r\n");
      out.write("        <script src=\"");
      out.print(basePath);
      out.write("/js/plugins/gritter/jquery.gritter.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <!-- Sparkline -->\r\n");
      out.write("        <script src=\"");
      out.print(basePath);
      out.write("/js/plugins/sparkline/jquery.sparkline.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <!-- Sparkline demo data  -->\r\n");
      out.write("        <script src=\"");
      out.print(basePath);
      out.write("/js/demo/sparkline-demo.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <!-- ChartJS-->\r\n");
      out.write("        <script src=\"");
      out.print(basePath);
      out.write("/js/plugins/chartJs/Chart.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <!-- Toastr -->\r\n");
      out.write("        <script src=\"");
      out.print(basePath);
      out.write("/js/plugins/toastr/toastr.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("        $(document).ready(function () {\r\n");
      out.write("            setTimeout(function () {\r\n");
      out.write("                toastr.options = {\r\n");
      out.write("                    closeButton: true,\r\n");
      out.write("                    progressBar: true,\r\n");
      out.write("                    showMethod: 'slideDown',\r\n");
      out.write("                    timeOut: 4000\r\n");
      out.write("                };\r\n");
      out.write("                toastr.success('Responsive Admin Theme', 'Welcome to INSPINIA');\r\n");
      out.write("\r\n");
      out.write("            }, 1300);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            var data1 = [\r\n");
      out.write("                [0, 4], [1, 8], [2, 5], [3, 10], [4, 4], [5, 16], [6, 5], [7, 11], [8, 6], [9, 11], [10, 30], [11, 10], [12, 13], [13, 4], [14, 3], [15, 3], [16, 6]\r\n");
      out.write("            ];\r\n");
      out.write("            var data2 = [\r\n");
      out.write("                [0, 1], [1, 0], [2, 2], [3, 0], [4, 1], [5, 3], [6, 1], [7, 5], [8, 2], [9, 3], [10, 2], [11, 1], [12, 0], [13, 2], [14, 8], [15, 0], [16, 0]\r\n");
      out.write("            ];\r\n");
      out.write("            $(\"#flot-dashboard-chart\").length && $.plot($(\"#flot-dashboard-chart\"), [\r\n");
      out.write("                data1, data2\r\n");
      out.write("            ],\r\n");
      out.write("                    {\r\n");
      out.write("                        series: {\r\n");
      out.write("                            lines: {\r\n");
      out.write("                                show: false,\r\n");
      out.write("                                fill: true\r\n");
      out.write("                            },\r\n");
      out.write("                            splines: {\r\n");
      out.write("                                show: true,\r\n");
      out.write("                                tension: 0.4,\r\n");
      out.write("                                lineWidth: 1,\r\n");
      out.write("                                fill: 0.4\r\n");
      out.write("                            },\r\n");
      out.write("                            points: {\r\n");
      out.write("                                radius: 0,\r\n");
      out.write("                                show: true\r\n");
      out.write("                            },\r\n");
      out.write("                            shadowSize: 2\r\n");
      out.write("                        },\r\n");
      out.write("                        grid: {\r\n");
      out.write("                            hoverable: true,\r\n");
      out.write("                            clickable: true,\r\n");
      out.write("                            tickColor: \"#d5d5d5\",\r\n");
      out.write("                            borderWidth: 1,\r\n");
      out.write("                            color: '#d5d5d5'\r\n");
      out.write("                        },\r\n");
      out.write("                        colors: [\"#1ab394\", \"#464f88\"],\r\n");
      out.write("                        xaxis: {\r\n");
      out.write("                        },\r\n");
      out.write("                        yaxis: {\r\n");
      out.write("                            ticks: 4\r\n");
      out.write("                        },\r\n");
      out.write("                        tooltip: false\r\n");
      out.write("                    }\r\n");
      out.write("            );\r\n");
      out.write("\r\n");
      out.write("            var doughnutData = [\r\n");
      out.write("                {\r\n");
      out.write("                    value: 300,\r\n");
      out.write("                    color: \"#a3e1d4\",\r\n");
      out.write("                    highlight: \"#1ab394\",\r\n");
      out.write("                    label: \"App\"\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    value: 50,\r\n");
      out.write("                    color: \"#dedede\",\r\n");
      out.write("                    highlight: \"#1ab394\",\r\n");
      out.write("                    label: \"Software\"\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    value: 100,\r\n");
      out.write("                    color: \"#b5b8cf\",\r\n");
      out.write("                    highlight: \"#1ab394\",\r\n");
      out.write("                    label: \"Laptop\"\r\n");
      out.write("                }\r\n");
      out.write("            ];\r\n");
      out.write("\r\n");
      out.write("            var doughnutOptions = {\r\n");
      out.write("                segmentShowStroke: true,\r\n");
      out.write("                segmentStrokeColor: \"#fff\",\r\n");
      out.write("                segmentStrokeWidth: 2,\r\n");
      out.write("                percentageInnerCutout: 45, // This is 0 for Pie charts\r\n");
      out.write("                animationSteps: 100,\r\n");
      out.write("                animationEasing: \"easeOutBounce\",\r\n");
      out.write("                animateRotate: true,\r\n");
      out.write("                animateScale: false,\r\n");
      out.write("            };\r\n");
      out.write("\r\n");
      out.write("            var ctx = document.getElementById(\"doughnutChart\").getContext(\"2d\");\r\n");
      out.write("            var DoughnutChart = new Chart(ctx).Doughnut(doughnutData, doughnutOptions);\r\n");
      out.write("\r\n");
      out.write("            var polarData = [\r\n");
      out.write("                {\r\n");
      out.write("                    value: 300,\r\n");
      out.write("                    color: \"#a3e1d4\",\r\n");
      out.write("                    highlight: \"#1ab394\",\r\n");
      out.write("                    label: \"App\"\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    value: 140,\r\n");
      out.write("                    color: \"#dedede\",\r\n");
      out.write("                    highlight: \"#1ab394\",\r\n");
      out.write("                    label: \"Software\"\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    value: 200,\r\n");
      out.write("                    color: \"#b5b8cf\",\r\n");
      out.write("                    highlight: \"#1ab394\",\r\n");
      out.write("                    label: \"Laptop\"\r\n");
      out.write("                }\r\n");
      out.write("            ];\r\n");
      out.write("\r\n");
      out.write("            var polarOptions = {\r\n");
      out.write("                scaleShowLabelBackdrop: true,\r\n");
      out.write("                scaleBackdropColor: \"rgba(255,255,255,0.75)\",\r\n");
      out.write("                scaleBeginAtZero: true,\r\n");
      out.write("                scaleBackdropPaddingY: 1,\r\n");
      out.write("                scaleBackdropPaddingX: 1,\r\n");
      out.write("                scaleShowLine: true,\r\n");
      out.write("                segmentShowStroke: true,\r\n");
      out.write("                segmentStrokeColor: \"#fff\",\r\n");
      out.write("                segmentStrokeWidth: 2,\r\n");
      out.write("                animationSteps: 100,\r\n");
      out.write("                animationEasing: \"easeOutBounce\",\r\n");
      out.write("                animateRotate: true,\r\n");
      out.write("                animateScale: false,\r\n");
      out.write("            };\r\n");
      out.write("            var ctx = document.getElementById(\"polarChart\").getContext(\"2d\");\r\n");
      out.write("            var Polarchart = new Chart(ctx).PolarArea(polarData, polarOptions);\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("        </script>\r\n");
      out.write("        <script>\r\n");
      out.write("        (function (i, s, o, g, r, a, m) {\r\n");
      out.write("            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {\r\n");
      out.write("                (i[r].q = i[r].q || []).push(arguments)\r\n");
      out.write("            }, i[r].l = 1 * new Date(); a = s.createElement(o),\r\n");
      out.write("                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)\r\n");
      out.write("        })(window, document, 'script', '../../www.google-analytics.com/analytics.js', 'ga');\r\n");
      out.write("\r\n");
      out.write("        ga('create', 'UA-4625583-2', 'webapplayers.com');\r\n");
      out.write("        ga('send', 'pageview');\r\n");
      out.write("\r\n");
      out.write("        </script>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tiles_005fgetAsString_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:getAsString
    org.apache.tiles.jsp.taglib.GetAsStringTag _jspx_th_tiles_005fgetAsString_005f0 = (new org.apache.tiles.jsp.taglib.GetAsStringTag());
    _jsp_instancemanager.newInstance(_jspx_th_tiles_005fgetAsString_005f0);
    _jspx_th_tiles_005fgetAsString_005f0.setJspContext(_jspx_page_context);
    // /WEB-INF/template/layout.jsp(14,11) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fgetAsString_005f0.setName("title");
    _jspx_th_tiles_005fgetAsString_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_tiles_005fgetAsString_005f0);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f0 = (new org.apache.tiles.jsp.taglib.InsertAttributeTag());
    _jsp_instancemanager.newInstance(_jspx_th_tiles_005finsertAttribute_005f0);
    _jspx_th_tiles_005finsertAttribute_005f0.setJspContext(_jspx_page_context);
    // /WEB-INF/template/layout.jsp(21,1) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f0.setName("header_js");
    // /WEB-INF/template/layout.jsp(21,1) name = ignore type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f0.setIgnore(true);
    _jspx_th_tiles_005finsertAttribute_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_tiles_005finsertAttribute_005f0);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f1 = (new org.apache.tiles.jsp.taglib.InsertAttributeTag());
    _jsp_instancemanager.newInstance(_jspx_th_tiles_005finsertAttribute_005f1);
    _jspx_th_tiles_005finsertAttribute_005f1.setJspContext(_jspx_page_context);
    // /WEB-INF/template/layout.jsp(22,1) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f1.setName("header_css");
    // /WEB-INF/template/layout.jsp(22,1) name = ignore type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f1.setIgnore(true);
    _jspx_th_tiles_005finsertAttribute_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_tiles_005finsertAttribute_005f1);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f2 = (new org.apache.tiles.jsp.taglib.InsertAttributeTag());
    _jsp_instancemanager.newInstance(_jspx_th_tiles_005finsertAttribute_005f2);
    _jspx_th_tiles_005finsertAttribute_005f2.setJspContext(_jspx_page_context);
    // /WEB-INF/template/layout.jsp(27,12) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f2.setName("leftmenu");
    _jspx_th_tiles_005finsertAttribute_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_tiles_005finsertAttribute_005f2);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f3 = (new org.apache.tiles.jsp.taglib.InsertAttributeTag());
    _jsp_instancemanager.newInstance(_jspx_th_tiles_005finsertAttribute_005f3);
    _jspx_th_tiles_005finsertAttribute_005f3.setJspContext(_jspx_page_context);
    // /WEB-INF/template/layout.jsp(30,20) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f3.setName("header");
    _jspx_th_tiles_005finsertAttribute_005f3.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_tiles_005finsertAttribute_005f3);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f4 = (new org.apache.tiles.jsp.taglib.InsertAttributeTag());
    _jsp_instancemanager.newInstance(_jspx_th_tiles_005finsertAttribute_005f4);
    _jspx_th_tiles_005finsertAttribute_005f4.setJspContext(_jspx_page_context);
    // /WEB-INF/template/layout.jsp(32,16) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f4.setName("breadcrumbs");
    _jspx_th_tiles_005finsertAttribute_005f4.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_tiles_005finsertAttribute_005f4);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f5 = (new org.apache.tiles.jsp.taglib.InsertAttributeTag());
    _jsp_instancemanager.newInstance(_jspx_th_tiles_005finsertAttribute_005f5);
    _jspx_th_tiles_005finsertAttribute_005f5.setJspContext(_jspx_page_context);
    // /WEB-INF/template/layout.jsp(35,17) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f5.setName("body");
    _jspx_th_tiles_005finsertAttribute_005f5.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_tiles_005finsertAttribute_005f5);
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f6 = (new org.apache.tiles.jsp.taglib.InsertAttributeTag());
    _jsp_instancemanager.newInstance(_jspx_th_tiles_005finsertAttribute_005f6);
    _jspx_th_tiles_005finsertAttribute_005f6.setJspContext(_jspx_page_context);
    // /WEB-INF/template/layout.jsp(41,6) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f6.setName("footer");
    // /WEB-INF/template/layout.jsp(41,6) name = ignore type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f6.setIgnore(true);
    _jspx_th_tiles_005finsertAttribute_005f6.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_tiles_005finsertAttribute_005f6);
    return false;
  }
}
