/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2015-07-08 09:39:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.template;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class leftmenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/EtaoJavaProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/admin/WEB-INF/lib/tiles-jsp-3.0.5.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1411313530000L));
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-3.0.5.jar", Long.valueOf(1435848268796L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String basePath = request.getContextPath();

      out.write("\r\n");
      out.write("<nav class=\"navbar-default navbar-static-side\" role=\"navigation\">\r\n");
      out.write("    <div class=\"sidebar-collapse\">\r\n");
      out.write("        <ul class=\"nav\" id=\"side-menu\">\r\n");
      out.write("            <li class=\"nav-header\">\r\n");
      out.write("                <div class=\"dropdown profile-element\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                        <img alt=\"image\" class=\"img-circle\" src=\"");
      out.print(basePath);
      out.write("/img/profile_small.jpg\" />\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">\r\n");
      out.write("                        <span class=\"clear\">\r\n");
      out.write("                            <span class=\"block m-t-xs\">\r\n");
      out.write("                                <strong class=\"font-bold\">admin</strong>\r\n");
      out.write("                            </span> <span class=\"text-muted text-xs block\">管理员 <b class=\"caret\"></b></span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu animated fadeInRight m-t-xs\">\r\n");
      out.write("                        <li><a href=\"profile.html\">个人信息</a></li>\r\n");
      out.write("                        <li><a href=\"contacts.html\">联系方式</a></li>\r\n");
      out.write("                        <li><a href=\"mailbox.html\">消息</a></li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li><a href=\"login.html\">注销</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"logo-element\">\r\n");
      out.write("                    IN+\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"active\">\r\n");
      out.write("                <a href=\"#\"><i class=\"fa fa-th-large\"></i> <span class=\"nav-label\">Dashboards</span> <span class=\"fa arrow\"></span></a>\r\n");
      out.write("                <ul class=\"nav nav-second-level\">\r\n");
      out.write("                      <li class=\"active\"><a href=\"index.html\">Dashboard v.1</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(basePath);
      out.write("/home/test\">Dashboard v.2</a></li>\r\n");
      out.write("                    <li><a href=\"dashboard_3.html\">Dashboard v.3</a></li>\r\n");
      out.write("                    <li><a href=\"dashboard_4_1.html\">Dashboard v.4</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"layouts.html\"><i class=\"fa fa-diamond\"></i> <span class=\"nav-label\">Layouts</span> <span class=\"label label-primary pull-right\">NEW</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\"><i class=\"fa fa-bar-chart-o\"></i> <span class=\"nav-label\">Graphs</span><span class=\"fa arrow\"></span></a>\r\n");
      out.write("                <ul class=\"nav nav-second-level\">\r\n");
      out.write("                    <li><a href=\"graph_flot.html\">Flot Charts</a></li>\r\n");
      out.write("                    <li><a href=\"graph_morris.html\">Morris.js Charts</a></li>\r\n");
      out.write("                    <li><a href=\"graph_rickshaw.html\">Rickshaw Charts</a></li>\r\n");
      out.write("                    <li><a href=\"graph_chartjs.html\">Chart.js</a></li>\r\n");
      out.write("                    <li><a href=\"graph_peity.html\">Peity Charts</a></li>\r\n");
      out.write("                    <li><a href=\"graph_sparkline.html\">Sparkline Charts</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"mailbox.html\"><i class=\"fa fa-envelope\"></i> <span class=\"nav-label\">Mailbox </span><span class=\"label label-warning pull-right\">16/24</span></a>\r\n");
      out.write("                <ul class=\"nav nav-second-level\">\r\n");
      out.write("                    <li><a href=\"mailbox.html\">Inbox</a></li>\r\n");
      out.write("                    <li><a href=\"mail_detail.html\">Email view</a></li>\r\n");
      out.write("                    <li><a href=\"mail_compose.html\">Compose email</a></li>\r\n");
      out.write("                    <li><a href=\"email_template.html\">Email templates</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"widgets.html\"><i class=\"fa fa-flask\"></i> <span class=\"nav-label\">Widgets</span> </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\"><i class=\"fa fa-edit\"></i> <span class=\"nav-label\">Forms</span><span class=\"fa arrow\"></span></a>\r\n");
      out.write("                <ul class=\"nav nav-second-level\">\r\n");
      out.write("                    <li><a href=\"form_basic.html\">Basic form</a></li>\r\n");
      out.write("                    <li><a href=\"form_advanced.html\">Advanced Plugins</a></li>\r\n");
      out.write("                    <li><a href=\"form_wizard.html\">Wizard</a></li>\r\n");
      out.write("                    <li><a href=\"form_file_upload.html\">File Upload</a></li>\r\n");
      out.write("                    <li><a href=\"form_editors.html\">Text Editor</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\"><i class=\"fa fa-desktop\"></i> <span class=\"nav-label\">App Views</span>  <span class=\"pull-right label label-primary\">SPECIAL</span></a>\r\n");
      out.write("                <ul class=\"nav nav-second-level\">\r\n");
      out.write("                    <li><a href=\"contacts.html\">Contacts</a></li>\r\n");
      out.write("                    <li><a href=\"profile.html\">Profile</a></li>\r\n");
      out.write("                    <li><a href=\"projects.html\">Projects</a></li>\r\n");
      out.write("                    <li><a href=\"project_detail.html\">Project detail</a></li>\r\n");
      out.write("                    <li><a href=\"teams_board.html\">Teams board</a></li>\r\n");
      out.write("                    <li><a href=\"clients.html\">Clients</a></li>\r\n");
      out.write("                    <li><a href=\"full_height.html\">Outlook view</a></li>\r\n");
      out.write("                    <li><a href=\"file_manager.html\">File manager</a></li>\r\n");
      out.write("                    <li><a href=\"calendar.html\">Calendar</a></li>\r\n");
      out.write("                    <li><a href=\"issue_tracker.html\">Issue tracker</a></li>\r\n");
      out.write("                    <li><a href=\"blog.html\">Blog</a></li>\r\n");
      out.write("                    <li><a href=\"article.html\">Article</a></li>\r\n");
      out.write("                    <li><a href=\"faq.html\">FAQ</a></li>\r\n");
      out.write("                    <li><a href=\"timeline.html\">Timeline</a></li>\r\n");
      out.write("                    <li><a href=\"pin_board.html\">Pin board</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\"><i class=\"fa fa-files-o\"></i> <span class=\"nav-label\">Other Pages</span><span class=\"fa arrow\"></span></a>\r\n");
      out.write("                <ul class=\"nav nav-second-level\">\r\n");
      out.write("                    <li><a href=\"search_results.html\">Search results</a></li>\r\n");
      out.write("                    <li><a href=\"lockscreen.html\">Lockscreen</a></li>\r\n");
      out.write("                    <li><a href=\"invoice.html\">Invoice</a></li>\r\n");
      out.write("                    <li><a href=\"login.html\">Login</a></li>\r\n");
      out.write("                    <li><a href=\"login_two_columns.html\">Login v.2</a></li>\r\n");
      out.write("                    <li><a href=\"forgot_password.html\">Forget password</a></li>\r\n");
      out.write("                    <li><a href=\"register.html\">Register</a></li>\r\n");
      out.write("                    <li><a href=\"404.html\">404 Page</a></li>\r\n");
      out.write("                    <li><a href=\"500.html\">500 Page</a></li>\r\n");
      out.write("                    <li><a href=\"empty_page.html\">Empty page</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\"><i class=\"fa fa-globe\"></i> <span class=\"nav-label\">Miscellaneous</span><span class=\"label label-info pull-right\">NEW</span></a>\r\n");
      out.write("                <ul class=\"nav nav-second-level\">\r\n");
      out.write("                    <li><a href=\"toastr_notifications.html\">Notification</a></li>\r\n");
      out.write("                    <li><a href=\"nestable_list.html\">Nestable list</a></li>\r\n");
      out.write("                    <li><a href=\"agile_board.html\">Agile board</a></li>\r\n");
      out.write("                    <li><a href=\"timeline_2.html\">Timeline v.2</a></li>\r\n");
      out.write("                    <li><a href=\"diff.html\">Diff</a></li>\r\n");
      out.write("                    <li><a href=\"idle_timer.html\">Idle timer</a></li>\r\n");
      out.write("                    <li><a href=\"spinners.html\">Spinners</a></li>\r\n");
      out.write("                    <li><a href=\"tinycon.html\">Live favicon</a></li>\r\n");
      out.write("                    <li><a href=\"google_maps.html\">Google maps</a></li>\r\n");
      out.write("                    <li><a href=\"code_editor.html\">Code editor</a></li>\r\n");
      out.write("                    <li><a href=\"modal_window.html\">Modal window</a></li>\r\n");
      out.write("                    <li><a href=\"forum_main.html\">Forum view</a></li>\r\n");
      out.write("                    <li><a href=\"validation.html\">Validation</a></li>\r\n");
      out.write("                    <li><a href=\"tree_view.html\">Tree view</a></li>\r\n");
      out.write("                    <li><a href=\"chat_view.html\">Chat view</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\"><i class=\"fa fa-flask\"></i> <span class=\"nav-label\">UI Elements</span><span class=\"fa arrow\"></span></a>\r\n");
      out.write("                <ul class=\"nav nav-second-level\">\r\n");
      out.write("                    <li><a href=\"typography.html\">Typography</a></li>\r\n");
      out.write("                    <li><a href=\"icons.html\">Icons</a></li>\r\n");
      out.write("                    <li><a href=\"draggable_panels.html\">Draggable Panels</a></li>\r\n");
      out.write("                    <li><a href=\"buttons.html\">Buttons</a></li>\r\n");
      out.write("                    <li><a href=\"video.html\">Video</a></li>\r\n");
      out.write("                    <li><a href=\"tabs_panels.html\">Tabs & Panels</a></li>\r\n");
      out.write("                    <li><a href=\"notifications.html\">Notifications & Tooltips</a></li>\r\n");
      out.write("                    <li><a href=\"badges_labels.html\">Badges, Labels, Progress</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"grid_options.html\"><i class=\"fa fa-laptop\"></i> <span class=\"nav-label\">Grid options</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\"><i class=\"fa fa-table\"></i> <span class=\"nav-label\">Tables</span><span class=\"fa arrow\"></span></a>\r\n");
      out.write("                <ul class=\"nav nav-second-level\">\r\n");
      out.write("                    <li><a href=\"table_basic.html\">Static Tables</a></li>\r\n");
      out.write("                    <li><a href=\"table_data_tables.html\">Data Tables</a></li>\r\n");
      out.write("                    <li><a href=\"jq_grid.html\">jqGrid</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\"><i class=\"fa fa-picture-o\"></i> <span class=\"nav-label\">Gallery</span><span class=\"fa arrow\"></span></a>\r\n");
      out.write("                <ul class=\"nav nav-second-level\">\r\n");
      out.write("                    <li><a href=\"basic_gallery.html\">Lightbox Gallery</a></li>\r\n");
      out.write("                    <li><a href=\"carousel.html\">Bootstrap Carusela</a></li>\r\n");
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\"><i class=\"fa fa-sitemap\"></i> <span class=\"nav-label\">Menu Levels </span><span class=\"fa arrow\"></span></a>\r\n");
      out.write("                <ul class=\"nav nav-second-level\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">Third Level <span class=\"fa arrow\"></span></a>\r\n");
      out.write("                        <ul class=\"nav nav-third-level\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Third Level Item</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Third Level Item</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Third Level Item</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"#\">Second Level Item</a></li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">Second Level Item</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">Second Level Item</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"css_animation.html\"><i class=\"fa fa-magic\"></i> <span class=\"nav-label\">CSS Animations </span><span class=\"label label-info pull-right\">62</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"landing_link\">\r\n");
      out.write("                <a target=\"_blank\" href=\"Landing_page/index.html\"><i class=\"fa fa-star\"></i> <span class=\"nav-label\">Landing Page</span> <span class=\"label label-warning pull-right\">NEW</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"special_link\">\r\n");
      out.write("                <a href=\"package.html\"><i class=\"fa fa-database\"></i> <span class=\"nav-label\">Package</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
