/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2015-07-08 09:52:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/EtaoJavaProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/admin/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1435834339131L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t  \r\n");

	String basePath = request.getContextPath();

      out.write("\r\n");
      out.write("<div class=\"row  border-bottom white-bg dashboard-header\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t<h2>Welcome Amelia</h2>\r\n");
      out.write("\t\t<small>You have 42 messages and 6 notifications.</small>\r\n");
      out.write("\t\t<ul class=\"list-group clear-list m-t\">\r\n");
      out.write("\t\t\t<li class=\"list-group-item fist-item\"><span class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t09:00 pm </span> <span class=\"label label-success\">1</span> Please contact\r\n");
      out.write("\t\t\t\tme</li>\r\n");
      out.write("\t\t\t<li class=\"list-group-item\"><span class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t10:16 am </span> <span class=\"label label-info\">2</span> Sign a contract</li>\r\n");
      out.write("\t\t\t<li class=\"list-group-item\"><span class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t08:22 pm </span> <span class=\"label label-primary\">3</span> Open new shop\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"list-group-item\"><span class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t11:06 pm </span> <span class=\"label label-default\">4</span> Call back to\r\n");
      out.write("\t\t\t\tSylvia</li>\r\n");
      out.write("\t\t\t<li class=\"list-group-item\"><span class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t12:00 am </span> <span class=\"label label-primary\">5</span> Write a letter\r\n");
      out.write("\t\t\t\tto Sandra</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t<div class=\"flot-chart dashboard-chart\">\r\n");
      out.write("\t\t\t<div class=\"flot-chart-content\" id=\"flot-dashboard-chart\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row text-left\">\r\n");
      out.write("\t\t\t<div class=\"col-xs-4\">\r\n");
      out.write("\t\t\t\t<div class=\" m-l-md\">\r\n");
      out.write("\t\t\t\t\t<span class=\"h4 font-bold m-t block\">$ 406,100</span> <small\r\n");
      out.write("\t\t\t\t\t\tclass=\"text-muted m-b block\">Sales marketing report</small>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-xs-4\">\r\n");
      out.write("\t\t\t\t<span class=\"h4 font-bold m-t block\">$ 150,401</span> <small\r\n");
      out.write("\t\t\t\t\tclass=\"text-muted m-b block\">Annual sales revenue</small>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-xs-4\">\r\n");
      out.write("\t\t\t\t<span class=\"h4 font-bold m-t block\">$ 16,822</span> <small\r\n");
      out.write("\t\t\t\t\tclass=\"text-muted m-b block\">Half-year revenue margin</small>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t<div class=\"statistic-box\">\r\n");
      out.write("\t\t\t<h4>Project Beta progress</h4>\r\n");
      out.write("\t\t\t<p>You have two project with not compleated task.</p>\r\n");
      out.write("\t\t\t<div class=\"row text-center\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t<canvas id=\"polarChart\" width=\"80\" height=\"80\"></canvas>\r\n");
      out.write("\t\t\t\t\t<h5>Kolter</h5>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t<canvas id=\"doughnutChart\" width=\"78\" height=\"78\"></canvas>\r\n");
      out.write("\t\t\t\t\t<h5>Maxtor</h5>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"m-t\">\r\n");
      out.write("\t\t\t\t<small>Lorem Ipsum is simply dummy text of the printing and\r\n");
      out.write("\t\t\t\t\ttypesetting industry.</small>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t<div class=\"wrapper wrapper-content\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"ibox float-e-margins\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ibox-title\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5>New data for the report</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"label label-primary\">IN+</span>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ibox-tools\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"collapse-link\"> <i class=\"fa fa-chevron-up\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-wrench\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-user\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Config option 1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Config option 2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"close-link\"> <i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ibox-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pull-right text-right\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"bar_dashboard\">5,3,9,6,5,9,7,3,5,2,4,7,3,2,7,9,6,4,5,7,3,2,1,0,9,5,6,8,3,2,1</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br /> <small class=\"font-bold\">$ 20 054.43</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tNYS report new data! <br /> <small class=\"m-r\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"graph_flot.html\"> Check the stock price! </a> </small>\r\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"ibox float-e-margins\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ibox-title\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5>Read below comments and tweets</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ibox-tools\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"collapse-link\"> <i class=\"fa fa-chevron-up\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-wrench\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-user\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Config option 1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Config option 2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"close-link\"> <i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ibox-content no-padding\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"list-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"list-group-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"text-info\" href=\"#\">Alan Marry</a> I belive that.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tLorem Ipsum is simply dummy text of the printing and\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttypesetting industry.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p> <small class=\"block text-muted\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-clock-o\"></i> 1 minuts ago</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"list-group-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"text-info\" href=\"#\">Stock Man</a> Check this stock\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tchart. This price is crazy!\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"text-center m\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span id=\"sparkline8\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div> <small class=\"block text-muted\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-clock-o\"></i> 2 hours ago</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"list-group-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"text-info\" href=\"#\">Kevin Smith</a> Lorem ipsum\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tunknown printer took a galley\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p> <small class=\"block text-muted\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-clock-o\"></i> 2 minuts ago</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"list-group-item \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"text-info\" href=\"#\">Jonathan Febrick</a> The\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstandard chunk of Lorem Ipsum\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p> <small class=\"block text-muted\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-clock-o\"></i> 1 hour ago</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"list-group-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"text-info\" href=\"#\">Alan Marry</a> I belive that.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tLorem Ipsum is simply dummy text of the printing and\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttypesetting industry.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p> <small class=\"block text-muted\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-clock-o\"></i> 1 minuts ago</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"list-group-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"text-info\" href=\"#\">Kevin Smith</a> Lorem ipsum\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tunknown printer took a galley\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p> <small class=\"block text-muted\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-clock-o\"></i> 2 minuts ago</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"ibox float-e-margins\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ibox-title\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5>Your daily feed</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ibox-tools\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"label label-warning-light\">10 Messages</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ibox-content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"feed-activity-list\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"feed-element\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"profile.html\" class=\"pull-left\"> <img alt=\"image\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"img-circle\" src=\"");
      out.print(basePath);
      out.write("/img/profile.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"media-body \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"pull-right\">5m ago</small> <strong>Monica\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tSmith</strong> posted a new blog. <br> <small class=\"text-muted\">Today\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t5:60 pm - 12.06.2014</small>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"feed-element\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"profile.html\" class=\"pull-left\"> <img alt=\"image\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"img-circle\" src=\"");
      out.print(basePath);
      out.write("/img/a2.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"media-body \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"pull-right\">2h ago</small> <strong>Mark\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tJohnson</strong> posted message on <strong>Monica Smith</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsite. <br> <small class=\"text-muted\">Today 2:10\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tpm - 12.06.2014</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"feed-element\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"profile.html\" class=\"pull-left\"> <img alt=\"image\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"img-circle\" src=\"");
      out.print(basePath);
      out.write("/img/a3.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"media-body \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"pull-right\">2h ago</small> <strong>Janet\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tRosowski</strong> add 1 photo on <strong>Monica Smith</strong>. <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"text-muted\">2 days ago at 8:30am</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"feed-element\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"profile.html\" class=\"pull-left\"> <img alt=\"image\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"img-circle\" src=\"");
      out.print(basePath);
      out.write("/img/a4.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"media-body \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"pull-right text-navy\">5h ago</small> <strong>Chris\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tJohnatan Overtunk</strong> started following <strong>Monica\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tSmith</strong>. <br> <small class=\"text-muted\">Yesterday\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t1:21 pm - 11.06.2014</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"actions\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"btn btn-xs btn-white\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-thumbs-up\"></i> Like </a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-xs btn-white\"><i class=\"fa fa-heart\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tLove</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"feed-element\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"profile.html\" class=\"pull-left\"> <img alt=\"image\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"img-circle\" src=\"");
      out.print(basePath);
      out.write("/img/a5.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"media-body \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"pull-right\">2h ago</small> <strong>Kim\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tSmith</strong> posted message on <strong>Monica Smith</strong> site.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br> <small class=\"text-muted\">Yesterday 5:20 pm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t- 12.06.2014</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"well\">Lorem Ipsum is simply dummy text of\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tthe printing and typesetting industry. Lorem Ipsum has been\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tthe industry's standard dummy text ever since the 1500s.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tOver the years, sometimes by accident, sometimes on purpose\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t(injected humour and the like).</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"btn btn-xs btn-white\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-thumbs-up\"></i> Like </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"feed-element\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"profile.html\" class=\"pull-left\"> <img alt=\"image\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"img-circle\" src=\"");
      out.print(basePath);
      out.write("/img/profile.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"media-body \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"pull-right\">23h ago</small> <strong>Monica\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tSmith</strong> love <strong>Kim Smith</strong>. <br> <small\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-muted\">2 days ago at 2:30 am -\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t11.06.2014</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"feed-element\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"profile.html\" class=\"pull-left\"> <img alt=\"image\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"img-circle\" src=\"");
      out.print(basePath);
      out.write("/img/a7.jpg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"media-body \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"pull-right\">46h ago</small> <strong>Mike\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tLoreipsum</strong> started following <strong>Monica Smith</strong>. <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<small class=\"text-muted\">3 days ago at 7:58 pm -\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t10.06.2014</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-primary btn-block m-t\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-arrow-down\"></i> Show More\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"ibox float-e-margins\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ibox-title\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5>Alpha project</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ibox-tools\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"collapse-link\"> <i class=\"fa fa-chevron-up\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a> <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-wrench\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-user\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Config option 1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Config option 2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"close-link\"> <i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ibox-content ibox-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>You have meeting today!</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<small><i class=\"fa fa-map-marker\"></i> Meeting is on\r\n");
      out.write("\t\t\t\t\t\t\t\t6:00am. Check your schedule to see detail.</small>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ibox-content inspinia-timeline\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xs-3 date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-briefcase\"></i> 6:00 am <br /> <small\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"text-navy\">2 hour ago</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xs-7 content no-top-border\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"m-b-xs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong>Meeting</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Conference on the sales results for the previous year.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tMonica please examine sales trends in marketing and products.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tBelow please find the current status of the sale.</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span data-diameter=\"40\" class=\"updating-chart\">5,3,9,6,5,9,7,3,5,2,5,3,9,6,5,9,4,7,3,2,9,8,7,4,5,1,2,9,5,4,7,2,7,7,3,5,2</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xs-3 date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-file-text\"></i> 7:00 am <br /> <small\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"text-navy\">3 hour ago</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xs-7 content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"m-b-xs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong>Send documents to Mike</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Lorem Ipsum is simply dummy text of the printing and\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttypesetting industry. Lorem Ipsum has been the industry's\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstandard dummy text ever since.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xs-3 date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-coffee\"></i> 8:00 am <br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xs-7 content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"m-b-xs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong>Coffee Break</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Go to shop and find some products. Lorem Ipsum is\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsimply dummy text of the printing and typesetting industry.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tLorem Ipsum has been the industry's.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xs-3 date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-phone\"></i> 11:00 am <br /> <small\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"text-navy\">21 hour ago</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xs-7 content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"m-b-xs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong>Phone with Jeronimo</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Lorem Ipsum has been the industry's standard dummy text\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tever since.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xs-3 date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-user-md\"></i> 09:00 pm <br /> <small>21\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thour ago</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xs-7 content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"m-b-xs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong>Go to the doctor dr Smith</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Find some issue and go to doctor.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xs-3 date\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-comments\"></i> 12:50 pm <br /> <small\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"text-navy\">48 hour ago</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xs-7 content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"m-b-xs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong>Chat with Monica and Sandra</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Web sites still in their infancy. Various versions have\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tevolved over the years, sometimes by accident, sometimes on\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tpurpose (injected humour and the like).</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
