package com.edaisong.core.sms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-11-10T11:12:25.518+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "SmsSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SmsSoap {

    @WebMethod(operationName = "SendSmsSaveLogNew", action = "http://tempuri.org/SendSmsSaveLogNew")
    @RequestWrapper(localName = "SendSmsSaveLogNew", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.SendSmsSaveLogNew")
    @ResponseWrapper(localName = "SendSmsSaveLogNewResponse", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.SendSmsSaveLogNewResponse")
    @WebResult(name = "SendSmsSaveLogNewResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String sendSmsSaveLogNew(
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "smsSource", targetNamespace = "http://tempuri.org/")
        java.lang.String smsSource,
        @WebParam(name = "supplierID", targetNamespace = "http://tempuri.org/")
        java.lang.Integer supplierID,
        @WebParam(name = "isVoiceSms", targetNamespace = "http://tempuri.org/")
        boolean isVoiceSms,
        @WebParam(name = "groupId", targetNamespace = "http://tempuri.org/")
        int groupId
    );

    @WebMethod(operationName = "SendSmsBase", action = "http://tempuri.org/SendSmsBase")
    @RequestWrapper(localName = "SendSmsBase", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.SendSmsBase")
    @ResponseWrapper(localName = "SendSmsBaseResponse", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.SendSmsBaseResponse")
    @WebResult(name = "SendSmsBaseResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String sendSmsBase(
        @WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "Content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        com.edaisong.core.sms.SmsSendType type
    );

    @WebMethod(operationName = "SendSmsResult", action = "http://tempuri.org/SendSmsResult")
    @RequestWrapper(localName = "SendSmsResult", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.SendSmsResult")
    @ResponseWrapper(localName = "SendSmsResultResponse", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.SendSmsResultResponse")
    @WebResult(name = "SendSmsResultResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String sendSmsResult(
        @WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "Content", targetNamespace = "http://tempuri.org/")
        java.lang.String content
    );

    @WebMethod(operationName = "MsgSendSms", action = "http://tempuri.org/MsgSendSms")
    @RequestWrapper(localName = "MsgSendSms", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.MsgSendSms")
    @ResponseWrapper(localName = "MsgSendSmsResponse", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.MsgSendSmsResponse")
    @WebResult(name = "MsgSendSmsResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String msgSendSms(
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content
    );

    @WebMethod(operationName = "SendSmsSaveLogB2B", action = "http://tempuri.org/SendSmsSaveLogB2B")
    @RequestWrapper(localName = "SendSmsSaveLogB2B", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.SendSmsSaveLogB2B")
    @ResponseWrapper(localName = "SendSmsSaveLogB2BResponse", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.SendSmsSaveLogB2BResponse")
    @WebResult(name = "SendSmsSaveLogB2BResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String sendSmsSaveLogB2B(
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "smsSource", targetNamespace = "http://tempuri.org/")
        java.lang.String smsSource,
        @WebParam(name = "supplierID", targetNamespace = "http://tempuri.org/")
        java.lang.Integer supplierID,
        @WebParam(name = "groupId", targetNamespace = "http://tempuri.org/")
        int groupId,
        @WebParam(name = "smsPlatform", targetNamespace = "http://tempuri.org/")
        java.lang.String smsPlatform
    );

    @WebMethod(operationName = "GetAllBlance", action = "http://tempuri.org/GetAllBlance")
    @RequestWrapper(localName = "GetAllBlance", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.GetAllBlance")
    @ResponseWrapper(localName = "GetAllBlanceResponse", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.GetAllBlanceResponse")
    @WebResult(name = "GetAllBlanceResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getAllBlance(
        @WebParam(name = "account", targetNamespace = "http://tempuri.org/")
        java.lang.String account,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        java.lang.String pwd
    );

    @WebMethod(operationName = "SendSmsSaveLogNoSign", action = "http://tempuri.org/SendSmsSaveLogNoSign")
    @RequestWrapper(localName = "SendSmsSaveLogNoSign", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.SendSmsSaveLogNoSign")
    @ResponseWrapper(localName = "SendSmsSaveLogNoSignResponse", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.SendSmsSaveLogNoSignResponse")
    @WebResult(name = "SendSmsSaveLogNoSignResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String sendSmsSaveLogNoSign(
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "smsSource", targetNamespace = "http://tempuri.org/")
        java.lang.String smsSource,
        @WebParam(name = "supplierID", targetNamespace = "http://tempuri.org/")
        java.lang.Integer supplierID,
        @WebParam(name = "isVoiceSms", targetNamespace = "http://tempuri.org/")
        boolean isVoiceSms
    );

    @WebMethod(operationName = "GetSendedSms", action = "http://tempuri.org/GetSendedSms")
    @RequestWrapper(localName = "GetSendedSms", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.GetSendedSms")
    @ResponseWrapper(localName = "GetSendedSmsResponse", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.GetSendedSmsResponse")
    @WebResult(name = "GetSendedSmsResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getSendedSms();

    @WebMethod(operationName = "VoiceSendSms", action = "http://tempuri.org/VoiceSendSms")
    @RequestWrapper(localName = "VoiceSendSms", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.VoiceSendSms")
    @ResponseWrapper(localName = "VoiceSendSmsResponse", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.VoiceSendSmsResponse")
    @WebResult(name = "VoiceSendSmsResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String voiceSendSms(
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "smsSource", targetNamespace = "http://tempuri.org/")
        java.lang.String smsSource,
        @WebParam(name = "supplierID", targetNamespace = "http://tempuri.org/")
        java.lang.Integer supplierID
    );

    @WebMethod(operationName = "SpeedSend", action = "http://tempuri.org/SpeedSend")
    @RequestWrapper(localName = "SpeedSend", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.SpeedSend")
    @ResponseWrapper(localName = "SpeedSendResponse", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.SpeedSendResponse")
    @WebResult(name = "SpeedSendResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String speedSend(
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "smsSource", targetNamespace = "http://tempuri.org/")
        java.lang.String smsSource,
        @WebParam(name = "supplierID", targetNamespace = "http://tempuri.org/")
        java.lang.Integer supplierID,
        @WebParam(name = "groupIdOrsign", targetNamespace = "http://tempuri.org/")
        java.lang.String groupIdOrsign
    );

    @WebMethod(operationName = "SendSms", action = "http://tempuri.org/SendSms")
    @RequestWrapper(localName = "SendSms", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.SendSms")
    @ResponseWrapper(localName = "SendSmsResponse", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.SendSmsResponse")
    @WebResult(name = "SendSmsResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String sendSms(
        @WebParam(name = "Mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "Content", targetNamespace = "http://tempuri.org/")
        java.lang.String content
    );

    @WebMethod(operationName = "MsgSendSmsSaveLog", action = "http://tempuri.org/MsgSendSmsSaveLog")
    @RequestWrapper(localName = "MsgSendSmsSaveLog", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.MsgSendSmsSaveLog")
    @ResponseWrapper(localName = "MsgSendSmsSaveLogResponse", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.MsgSendSmsSaveLogResponse")
    @WebResult(name = "MsgSendSmsSaveLogResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String msgSendSmsSaveLog(
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        com.edaisong.core.sms.SmsSendType type,
        @WebParam(name = "smsSource", targetNamespace = "http://tempuri.org/")
        java.lang.String smsSource,
        @WebParam(name = "supplierID", targetNamespace = "http://tempuri.org/")
        java.lang.Integer supplierID
    );

    @WebMethod(operationName = "SendSmsBaseSaveLog", action = "http://tempuri.org/SendSmsBaseSaveLog")
    @RequestWrapper(localName = "SendSmsBaseSaveLog", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.SendSmsBaseSaveLog")
    @ResponseWrapper(localName = "SendSmsBaseSaveLogResponse", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.SendSmsBaseSaveLogResponse")
    @WebResult(name = "SendSmsBaseSaveLogResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String sendSmsBaseSaveLog(
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        com.edaisong.core.sms.SmsSendType type,
        @WebParam(name = "smsSource", targetNamespace = "http://tempuri.org/")
        java.lang.String smsSource,
        @WebParam(name = "supplierID", targetNamespace = "http://tempuri.org/")
        java.lang.Integer supplierID
    );

    @WebMethod(operationName = "SendSmsSaveLog", action = "http://tempuri.org/SendSmsSaveLog")
    @RequestWrapper(localName = "SendSmsSaveLog", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.SendSmsSaveLog")
    @ResponseWrapper(localName = "SendSmsSaveLogResponse", targetNamespace = "http://tempuri.org/", className = "com.edaisong.core.sms.SendSmsSaveLogResponse")
    @WebResult(name = "SendSmsSaveLogResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String sendSmsSaveLog(
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "smsSource", targetNamespace = "http://tempuri.org/")
        java.lang.String smsSource,
        @WebParam(name = "supplierID", targetNamespace = "http://tempuri.org/")
        java.lang.Integer supplierID,
        @WebParam(name = "isVoiceSms", targetNamespace = "http://tempuri.org/")
        boolean isVoiceSms
    );
}
