
package com.edaisong.core.sms;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-11-10T11:12:25.423+08:00
 * Generated source version: 3.0.4
 * 
 */
public final class SmsSoap_SmsSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "Sms");

    private SmsSoap_SmsSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Sms.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Sms ss = new Sms(wsdlURL, SERVICE_NAME);
        SmsSoap port = ss.getSmsSoap();  
        
        {
        System.out.println("Invoking sendSmsSaveLogNew...");
        java.lang.String _sendSmsSaveLogNew_mobile = "";
        java.lang.String _sendSmsSaveLogNew_content = "";
        java.lang.String _sendSmsSaveLogNew_smsSource = "";
        java.lang.Integer _sendSmsSaveLogNew_supplierID = null;
        boolean _sendSmsSaveLogNew_isVoiceSms = false;
        int _sendSmsSaveLogNew_groupId = 0;
        java.lang.String _sendSmsSaveLogNew__return = port.sendSmsSaveLogNew(_sendSmsSaveLogNew_mobile, _sendSmsSaveLogNew_content, _sendSmsSaveLogNew_smsSource, _sendSmsSaveLogNew_supplierID, _sendSmsSaveLogNew_isVoiceSms, _sendSmsSaveLogNew_groupId);
        System.out.println("sendSmsSaveLogNew.result=" + _sendSmsSaveLogNew__return);


        }
        {
        System.out.println("Invoking sendSmsBase...");
        java.lang.String _sendSmsBase_mobile = "";
        java.lang.String _sendSmsBase_content = "";
        com.edaisong.core.sms.SmsSendType _sendSmsBase_type = null;
        java.lang.String _sendSmsBase__return = port.sendSmsBase(_sendSmsBase_mobile, _sendSmsBase_content, _sendSmsBase_type);
        System.out.println("sendSmsBase.result=" + _sendSmsBase__return);


        }
        {
        System.out.println("Invoking sendSmsResult...");
        java.lang.String _sendSmsResult_mobile = "";
        java.lang.String _sendSmsResult_content = "";
        java.lang.String _sendSmsResult__return = port.sendSmsResult(_sendSmsResult_mobile, _sendSmsResult_content);
        System.out.println("sendSmsResult.result=" + _sendSmsResult__return);


        }
        {
        System.out.println("Invoking msgSendSms...");
        java.lang.String _msgSendSms_mobile = "";
        java.lang.String _msgSendSms_content = "";
        java.lang.String _msgSendSms__return = port.msgSendSms(_msgSendSms_mobile, _msgSendSms_content);
        System.out.println("msgSendSms.result=" + _msgSendSms__return);


        }
        {
        System.out.println("Invoking sendSmsSaveLogB2B...");
        java.lang.String _sendSmsSaveLogB2B_mobile = "";
        java.lang.String _sendSmsSaveLogB2B_content = "";
        java.lang.String _sendSmsSaveLogB2B_smsSource = "";
        java.lang.Integer _sendSmsSaveLogB2B_supplierID = null;
        int _sendSmsSaveLogB2B_groupId = 0;
        java.lang.String _sendSmsSaveLogB2B_smsPlatform = "";
        java.lang.String _sendSmsSaveLogB2B__return = port.sendSmsSaveLogB2B(_sendSmsSaveLogB2B_mobile, _sendSmsSaveLogB2B_content, _sendSmsSaveLogB2B_smsSource, _sendSmsSaveLogB2B_supplierID, _sendSmsSaveLogB2B_groupId, _sendSmsSaveLogB2B_smsPlatform);
        System.out.println("sendSmsSaveLogB2B.result=" + _sendSmsSaveLogB2B__return);


        }
        {
        System.out.println("Invoking getAllBlance...");
        java.lang.String _getAllBlance_account = "";
        java.lang.String _getAllBlance_pwd = "";
        java.lang.String _getAllBlance__return = port.getAllBlance(_getAllBlance_account, _getAllBlance_pwd);
        System.out.println("getAllBlance.result=" + _getAllBlance__return);


        }
        {
        System.out.println("Invoking sendSmsSaveLogNoSign...");
        java.lang.String _sendSmsSaveLogNoSign_mobile = "";
        java.lang.String _sendSmsSaveLogNoSign_content = "";
        java.lang.String _sendSmsSaveLogNoSign_smsSource = "";
        java.lang.Integer _sendSmsSaveLogNoSign_supplierID = null;
        boolean _sendSmsSaveLogNoSign_isVoiceSms = false;
        java.lang.String _sendSmsSaveLogNoSign__return = port.sendSmsSaveLogNoSign(_sendSmsSaveLogNoSign_mobile, _sendSmsSaveLogNoSign_content, _sendSmsSaveLogNoSign_smsSource, _sendSmsSaveLogNoSign_supplierID, _sendSmsSaveLogNoSign_isVoiceSms);
        System.out.println("sendSmsSaveLogNoSign.result=" + _sendSmsSaveLogNoSign__return);


        }
        {
        System.out.println("Invoking getSendedSms...");
        java.lang.String _getSendedSms__return = port.getSendedSms();
        System.out.println("getSendedSms.result=" + _getSendedSms__return);


        }
        {
        System.out.println("Invoking voiceSendSms...");
        java.lang.String _voiceSendSms_mobile = "";
        java.lang.String _voiceSendSms_content = "";
        java.lang.String _voiceSendSms_smsSource = "";
        java.lang.Integer _voiceSendSms_supplierID = null;
        java.lang.String _voiceSendSms__return = port.voiceSendSms(_voiceSendSms_mobile, _voiceSendSms_content, _voiceSendSms_smsSource, _voiceSendSms_supplierID);
        System.out.println("voiceSendSms.result=" + _voiceSendSms__return);


        }
        {
        System.out.println("Invoking speedSend...");
        java.lang.String _speedSend_mobile = "";
        java.lang.String _speedSend_content = "";
        java.lang.String _speedSend_smsSource = "";
        java.lang.Integer _speedSend_supplierID = null;
        java.lang.String _speedSend_groupIdOrsign = "";
        java.lang.String _speedSend__return = port.speedSend(_speedSend_mobile, _speedSend_content, _speedSend_smsSource, _speedSend_supplierID, _speedSend_groupIdOrsign);
        System.out.println("speedSend.result=" + _speedSend__return);


        }
        {
        System.out.println("Invoking sendSms...");
        java.lang.String _sendSms_mobile = "";
        java.lang.String _sendSms_content = "";
        java.lang.String _sendSms__return = port.sendSms(_sendSms_mobile, _sendSms_content);
        System.out.println("sendSms.result=" + _sendSms__return);


        }
        {
        System.out.println("Invoking msgSendSmsSaveLog...");
        java.lang.String _msgSendSmsSaveLog_mobile = "";
        java.lang.String _msgSendSmsSaveLog_content = "";
        com.edaisong.core.sms.SmsSendType _msgSendSmsSaveLog_type = null;
        java.lang.String _msgSendSmsSaveLog_smsSource = "";
        java.lang.Integer _msgSendSmsSaveLog_supplierID = null;
        java.lang.String _msgSendSmsSaveLog__return = port.msgSendSmsSaveLog(_msgSendSmsSaveLog_mobile, _msgSendSmsSaveLog_content, _msgSendSmsSaveLog_type, _msgSendSmsSaveLog_smsSource, _msgSendSmsSaveLog_supplierID);
        System.out.println("msgSendSmsSaveLog.result=" + _msgSendSmsSaveLog__return);


        }
        {
        System.out.println("Invoking sendSmsBaseSaveLog...");
        java.lang.String _sendSmsBaseSaveLog_mobile = "";
        java.lang.String _sendSmsBaseSaveLog_content = "";
        com.edaisong.core.sms.SmsSendType _sendSmsBaseSaveLog_type = null;
        java.lang.String _sendSmsBaseSaveLog_smsSource = "";
        java.lang.Integer _sendSmsBaseSaveLog_supplierID = null;
        java.lang.String _sendSmsBaseSaveLog__return = port.sendSmsBaseSaveLog(_sendSmsBaseSaveLog_mobile, _sendSmsBaseSaveLog_content, _sendSmsBaseSaveLog_type, _sendSmsBaseSaveLog_smsSource, _sendSmsBaseSaveLog_supplierID);
        System.out.println("sendSmsBaseSaveLog.result=" + _sendSmsBaseSaveLog__return);


        }
        {
        System.out.println("Invoking sendSmsSaveLog...");
        java.lang.String _sendSmsSaveLog_mobile = "";
        java.lang.String _sendSmsSaveLog_content = "";
        java.lang.String _sendSmsSaveLog_smsSource = "";
        java.lang.Integer _sendSmsSaveLog_supplierID = null;
        boolean _sendSmsSaveLog_isVoiceSms = false;
        java.lang.String _sendSmsSaveLog__return = port.sendSmsSaveLog(_sendSmsSaveLog_mobile, _sendSmsSaveLog_content, _sendSmsSaveLog_smsSource, _sendSmsSaveLog_supplierID, _sendSmsSaveLog_isVoiceSms);
        System.out.println("sendSmsSaveLog.result=" + _sendSmsSaveLog__return);


        }

        System.exit(0);
    }

}
